@extends('layouts.template')

@section('content')
	
	<!--================About Area =================-->
	<section class="latest_blog_area  color-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="main_title">
						
						<h3 style=" font-family: ML-TTKarthika;">
							
						</div>
					</div>
				</div>
				<div class="bottom_part history">
					<p class="history" style="align:center;text-align: justify">
                    <p style="margin: 9pt 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><span style="font-size: 14.0pt; font-family: 'Nirmala UI', sans-serif; color: red;">ചെറിയ ഒപ്പീസ്</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">(</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സംക്ഷിപ്ത രൂപത്തിലുള്ള ഒപ്പീസ്)</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ശുശ്രൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മരിച്ചവരെ ഉയിര്&zwj;പ്പിക്കുന്നവനേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്റെ തിരുനാമത്തിനു സ്തുതി. നമുക്കു പ്രാര്&zwj;ത്ഥിക്കാം</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">; </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമാധാനം നമ്മോടുകൂടെ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സ്ലോസാ</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കരുണയുള്ള കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കരയുന്നവര്&zwj; നിന്നെ വിളിക്കുകയും സങ്കടപ്പെടുന്നവര്&zwj; നിന്നെ ആശ്രയിക്കുകയും ചെയ്യുന്നു. നിന്റെ വാഗ്ദാനങ്ങളുടെ പ്രതീക്ഷയാല്&zwj; നിന്റെ ദാസനെ ആശ്വസിപ്പിക്കേണമേ. ജീവന്റെയും മരണത്തിന്റെയും നാഥനും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പിതാവും പുത്രനും പരിശുദ്ധാത്മാവുമായ സര്&zwj;വ്വേശ്വരാ.</span></p>
<p style="margin: 0cm 0cm 7.5pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആമ്മേന്&zwj;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഒനീസാ</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br />(</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മല്&zwj;ക്കാ മിശിഹാ...)</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">എന്റെ കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്നെ ഞാന്&zwj; പ്രകീര്&zwj;ത്തിക്കും</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മഹിമയോടന്തിമ വിധിനാളില്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നീയണയുമ്പോള്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കരുണയൊടെന്നെ നിറുത്തണമേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നല്ലവരൊത്തു വലംഭാഗേ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്നെ ഞാനാശ്രയിച്ചു</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്&zwj; കുരിശിനെ ഞാ-</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നാരാധിച്ചുവണങ്ങുന്നു.</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അതുതാന്&zwj; ഞങ്ങള്&zwj;ക്കുത്ഥാനം</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">രക്ഷയുമുയിരും നല്&zwj;കുന്നു.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആകാശവും ഭൂമിയും നിന്റേതാകുന്നു</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആകാശവുമീഭൂതലവും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">താവകമല്ലോ കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ജീവിക്കുന്നവനഭയം നീ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നല്&zwj;കണമേ മൃതനായുസ്സും.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അവരാനന്ദകീര്&zwj;ത്തനങ്ങള്&zwj; പാടും</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മൃതരാം നരരുടെ പാപങ്ങള്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മായ്ക്കണമേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്&zwj; കൃപയാലേ:</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മാമ്മോദീസാ വഴിയങ്ങേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സുതരാണവരെന്നോര്&zwj;ക്കണമേ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അവന്റെ സന്തോഷത്തില്&zwj; അവരാനന്ദിക്കും</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്&zwj; ശോണിതവും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ദിവ്യശരീരവുമറിവോടെ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഉള്&zwj;ക്കൊണ്ടവരാം നിന്&zwj; സുതരേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിത്യവിരുന്നില്&zwj; ചേര്&zwj;ക്കണമേ</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അവരിലാരും അവശേഷിച്ചില്ല</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മഴപെയ്യുമ്പോള്&zwj; വയലുകളില്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">വിത്തുകള്&zwj; പൊട്ടിമുളയ്ക്കുന്നു.</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാഹളനാദം കേള്&zwj;ക്കുമ്പോള്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മൃതരില്&zwj; ജീവനുദിക്കുന്നു.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പിതാവിനും പുത്രനും പരിശുദ്ധാത്മാവിനും സ്തുതി</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ബാവാ പുത്രന്&zwj; റൂഹായേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">,<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മൃതനാമെന്നില്&zwj; കനിയേണം</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ജീവന്&zwj; നല്&zwj;കി മഹോന്നതമാം</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പ്രഭയുടെ നാട്ടില്&zwj; ചേര്&zwj;ക്കേണം.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആദിമുതല്&zwj; എന്നേയ്ക്കും ആമ്മേന്&zwj;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">തെളിവായെന്നുടെ നാഥാ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">തിരുമിഴിയെല്ലാം കാണുന്നു</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിരവധിയാമെന്&zwj; പാപങ്ങള്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;<br /></span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിരയായെണ്ണി വിധിക്കല്ലേ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ശുശ്രൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നമ്മുക്കു പ്രാര്&zwj;ത്ഥിക്കാം</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">; </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമാധാനം നമ്മോടുകൂടെ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സ്ലോസാ</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്റെ കരുണ ഞങ്ങളെ അനുഗമിക്കുകയും നിന്റെ ദയാധിക്യം ഞങ്ങളുടെ പാപങ്ങള്&zwj; മായിച്ചുകളയുകയും ചെയ്യുമാറാകട്ടെ. മഹനീയമായ നിന്റെ ത്രിത്വത്തിന്റെ അനുഗ്രഹം ഞങ്ങളെ സഹായിക്കുമാറാകട്ടെ. ജീവന്റെയും മരണത്തിന്റെയും നാഥനും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പിതാവും പുത്രനും പരിശുദ്ധാത്മാവുമായ സര്&zwj;വ്വേശ്വരാ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">എന്നേയ്ക്കും.</span></p>
<p style="margin: 0cm 0cm 7.5pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആമ്മേന്&zwj; . കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അനുഗ്രഹിക്കേണമേ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഹാസാ</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നീ ആകാശത്തിലും ഭൂമിയിലും സ്തുത്യര്&zwj;ഹനാകുന്നു. ഞങ്ങളുടെ ജീവന്റെ കാരണവും ആത്മാവിന്റെ പ്രത്യാശയും നീയാകുന്നു. ജീവന്റെയും മരണത്തിന്റെയും നാഥനും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പിതാവും പുത്രനും പരിശുദ്ധാത്മാവുമായ സര്&zwj;വ്വേശ്വരാ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">എന്നേയ്ക്കും.</span></p>
<p style="margin: 0cm 0cm 7.5pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആമ്മേന്&zwj;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മദ്&zwj;രാശ</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">{</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കുര്&zwj;ബ്ബാന കഴിഞ്ഞ ഉടനെയാണെങ്കില്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">}</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">(</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കമ്പെന്&zwj;&zwj;മാറാന്&zwj; ...)</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കൈക്കൊള്ളണമേ ഹൃദയം&zwj;ഗമമാം</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">വിശ്വാസമൊടെ ദാസന്&zwj; ചെയ്യുംബലിയെന്&zwj;&zwj;നാഥാതിരുസ്സന്നിധിയില്&zwj;</span></p>
<p style="margin: 0cm 0cm 7.5pt; text-indent: 36pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കൈക്കൊള്ളണമേ...</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പൂര്&zwj;വ്വന്മാരാം നോഹ്&zwj;അബ്രാഹം</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഇസഹാക്ക് യാക്കോബ് മഹിതാശയര്&zwj; തന്&zwj;പരിപാവനമാം ബലികള്&zwj; പോലെ.</span></p>
<p style="margin: 0cm 0cm 7.5pt; text-indent: 36pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കൈക്കൊള്ളണമേ...</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പുരുവത്സലരാം ശ്ലീഹരുമൊരുപോല്&zwj;വിനയാന്വിതരായ് തവസന്നിധിയില്&zwj;ചെയ്തൊരു നവമാം ബലിപോല്&zwj; നാഥാ</span></p>
<p style="margin: 0cm 0cm 7.5pt; text-indent: 36pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കൈക്കൊള്ളണമേ...</span></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">{</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മറ്റവസരങ്ങളില്&zwj;</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">}</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">(</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ലാതക് റേലാക്)</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഉന്നതനൃപനാം മിശിഹാനാഥാ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മൃതരെല്ലാരും മിന്നിവിളങ്ങും വദനമൊടുണരാന്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">വരമരുളേണം</span></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: justify; text-indent: 36pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഉന്നതനൃപനാം...</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">വിധിയുടെ നാളില്&zwj;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">വിജയപ്രഭയില്&zwj; വിണ്ടലമെങ്ങും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പൊങ്ങിമുഴങ്ങും കാഹളനാദം പൂജിതമല്ലോ</span></p>
<p style="margin: 0cm 0cm 7.5pt; text-indent: 36pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഉന്നതനൃപനാം...</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അന്ത്യമെഴാത്തോരവികലമോദംനുകരാന്&zwj; മൃതരെമഹിമാവൊഴുകും മണവറയിങ്കല്&zwj; ചേര്&zwj;ക്കണമീശോ.</span></p>
<p style="margin: 0cm 0cm 7.5pt; text-indent: 36pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഉന്നതനൃപനാം...</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ശൂറായ</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;(</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സങ്കീ. </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">129)</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ശുശ്രൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അഗാധത്തില്&zwj; നിന്നു നിന്നെ ഞാന്&zwj; വിളിക്കുന്നു. മരിച്ചവരെ ഉയിര്&zwj;പ്പിക്കുന്നവനെ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്റെ&nbsp; തിരുനാമത്തിനു സ്തുതി.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><em><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">(</span></em><em><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂഹം രണ്ടുഗണമായി തുടരുന്നു)</span></em></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അഗാധത്തില്&zwj; നിന്നു നിന്നെ ഞാന്&zwj; വിളിക്കുന്നു. കര്&zwj;ത്താവേ എന്റെ ശബ്ദം കേള്&zwj;ക്കണമേ.</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">എന്റെ പ്രാര്&zwj;ത്ഥന ചെവിക്കൊള്ളണമേ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കര്&zwj;ത്താവേ</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നീ പാപങ്ങളെല്ലാം ഓര്&zwj;ത്തിരിക്കുമെങ്കില്&zwj; ആര്&zwj;ക്കു രക്ഷയുണ്ടാകും</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">?<br /></span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">എന്തുകൊണ്ടെന്നാല്&zwj; പാപമോചനം നിന്റെ പക്കല്&zwj; നിന്നാകുന്നുവല്ലോ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കര്&zwj;ത്താവില്&zwj; ഞാന്&zwj; ശരണപ്പെടുന്നു.</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">എന്റെ പ്രതീക്ഷ അവന്റെ വാഗ്ദാനത്തിലാകുന്നു.</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /><br /></span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പുലരിയാവാന്&zwj; കാത്തിരിക്കുന്ന കാവല്&zwj;ക്കാരെപ്പോലെ കര്&zwj;ത്താവേ</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്നെ ഞാന്&zwj; കാത്തിരിക്കുന്നു.</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പുലരിയാവാന്&zwj; കാത്തിരിക്കുന്ന കാവല്&zwj;ക്കാരെപ്പോലെ ഇസ്രായേലും കര്&zwj;ത്താവിനെ കാത്തിരിക്കുന്നു.</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /><br /></span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">എന്തുകൊണ്ടെന്നാല്&zwj; അവന്&zwj; കരുണയുള്ളവനാകുന്നു.</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പൂര്&zwj;ണ്ണമായ രക്ഷയും അവന്റെ പക്കലാകുന്നു.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഇസ്രായേലിനെ അതിന്റെ പാപങ്ങളില്&zwj; നിന്നെല്ലാം അവന്&zwj; രക്ഷിക്കും.</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പിതാവിനും പുത്രനും പരിശുദ്ധാത്മാവിനും സ്തുതി.</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;"><br /></span><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആദിമുതല്&zwj; എന്നേയ്ക്കും ആമ്മേന്&zwj;</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ശുശ്രൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അഗാധത്തില്&zwj; നിന്നു നിന്നെ ഞാന്&zwj; വിളിക്കുന്നു. മരിച്ചവരെ ഉയിര്&zwj;പ്പിക്കുന്നവനെ നിന്റെ തിരുനാമത്തിനു സ്തുതി. നമ്മുക്കു പ്രാര്&zwj;ത്ഥിക്കാം</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമാധാനം നമ്മോടുകൂടെ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സ്ലോസ</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സജീവവും ജീവദായകവുമായ ശബ്ദത്താല്&zwj; ലാസറിനെ ഉയിര്&zwj;പ്പിച്ച കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആ ശബ്ദം മഹനീയമായ നീതിവിധിയുടെ ദിവസത്തില്&zwj; നിന്റെ ദാസനെ (ദാസിയെ) വിളിക്കുകയും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്റെ വലത്തുഭാഗത്തു നിറുത്തുകയും ചെയ്യട്ടെ. പാപങ്ങള്&zwj; പൊറുക്കുന്നവനും കരുണനിറഞ്ഞവനും നീതിമാനുമായ വിധികര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ജീവന്റെയും മരണത്തിന്റെയും നാഥനും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പിതാവും പുത്രനും പരിശുദ്ധാത്മാവുമായ സര്&zwj;വ്വേശ്വരാ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">എന്നേയ്ക്കും.</span></p>
<p style="margin: 0cm 0cm 7.5pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആമ്മേന്&zwj; . കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അനുഗ്രഹിക്കേണമേ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഹാസാ</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മരിച്ചവരെ നീ കരുണാപൂര്&zwj;വ്വം ജീവിപ്പിക്കണമേ. ജീവിക്കുന്നവരെ ദയാപൂര്&zwj;വ്വം പരിപാലിക്കേണമേ. ഉത്ഥാനം പ്രതീക്ഷിച്ചു മരണമടഞ്ഞവരെ ജീ മഹിമയോടുകൂടെ ഉയിര്&zwj;പ്പിക്കേണമേ. ജീവന്റെയും മരണത്തിന്റെയും നാഥനും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">പിതാവും പുത്രനും പരിശുദ്ധാത്മാവുമായ സര്&zwj;വ്വേശ്വരാ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">എന്നേയ്ക്കും.</span></p>
<p style="margin: 0cm 0cm 7.5pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആമ്മേന്&zwj; . കര്&zwj;ത്താവേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">അനുഗ്രഹിക്കേണമേ.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ഹൂത്താമ്മ</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">കാര്&zwj;മ്മി:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സകലത്തിന്റെയും നാഥനും ദൈവവുമായ മിശിഹായേ</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">നിന്റെ കുരിശിന്റെ അടയാളത്തോടും ദൈവദൂതന്മാരുടെ അകമ്പടിയോടും കൂടെ വാനമേഘങ്ങളില്&zwj; നീ പ്രത്യക്ഷനാവുകയും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സ്വര്&zwj;ഗ്ഗരാജ്യത്തിന്റെ വാതിലുകള്&zwj; തുറക്കപ്പെടുകയും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">മരിച്ചവര്&zwj; അക്ഷയരായി കവറിടങ്ങളില്&zwj; നിന്നുയിര്&zwj;ക്കുകയും</span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">, </span><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ദുഷ്ടജനങ്ങള്&zwj; നീതിമാന്മാരില്&zwj;നിന്നു വേര്&zwj;തിരിക്കപ്പെടുകയും ചെയ്യുന്ന ഭയാനകമായ വിധിദിവസത്തില്&zwj; നിന്റെ തിരഞ്ഞെടുക്കപ്പെട്ടവര്&zwj;ക്കായി ലോകാരംഭത്തില്&zwj; തന്നെ സജ്ജമാക്കപ്പെട്ടിരിക്കുന്ന സ്വര്&zwj;ഗ്ഗരാജ്യത്തിലേയ്ക്കു ഞങ്ങളുടെ ഈ സഹോദരനെ (സഹോദരിയെ) നീ സ്വീകരിക്കേണമേ. ഞങ്ങളിലും ഞങ്ങളുടെ സമൂഹത്തിലും നിന്റെ കൃപയും അനുഗ്രഹവും നിരന്തരം വസിക്കുമാറാകട്ടെ. ഇപ്പോഴും എപ്പോഴും എന്നേയ്ക്കും.</span></p>
<p style="margin: 0cm 0cm 7.5pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;"><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">സമൂ:</span></strong><strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">&nbsp;</span></strong><span style="font-family: 'Nirmala UI', sans-serif; color: #333333;">ആമ്മേന്&zwj;</span></p>
<p style="margin: 0cm 0cm 8pt; line-height: 106%; font-size: 11pt; font-family: Calibri, sans-serif;"><a name="_GoBack"></a>&nbsp;</p>


	                </p>



							
						</div>
						<!-- <a href="#" class="main_btn mt-45">Request Custom Price</a> -->
					
				
			
			
		</div>
	</section>
	<!--================End About Area =================-->


@endsection