@extends('layouts.template')

@section('content')
	
	<!--================About Area =================-->
	<section class="latest_blog_area section_gap color-bg">
		<div class="container novena">
			<div class="row">
				<div class="col-lg-12">
					<div class="main_title">
						<div class="top-part">
							<p></p>
						</div>
				


						</div>
					</div>
				</div>
				<div class="bottom_part novena">

						<ul style="margin-top: 0cm; margin-bottom: 6.0pt;">
<li style="margin: 0cm 0cm 6pt 168px; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #374142;">മംഗലവാര്&zwj;ത്തക്കാലം</span></li>
<li style="margin: 0cm 0cm 6pt 168px; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #374142;">പിറവിക്കാലം</span></li>
<li style="margin: 0cm 0cm 6pt 168px; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #374142;">ദനഹാകാലം</span></li>
<li style="margin: 0cm 0cm 6pt 168px; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #374142;">നോയമ്പ്ക്കാലം</span><a name="_GoBack"></a></li>
<li style="margin: 0cm 0cm 6pt 168px; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #374142;">ഉയിര്&zwj;പ്പുകാലം</span></li>
<li style="margin: 0cm 0cm 6pt 168px; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #374142;">ശ്ളീഹാക്കാലം</span></li>
<li style="margin: 0cm 0cm 6pt 168px; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #374142;">കൈത്താക്കാലം</span></li>
<li style="margin: 0cm 0cm 6pt 168px; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #374142;">എലിയാ ശ്ലീഹ മൂശാ കാലം</span></li>
<li style="margin: 0cm 0cm 6pt 168px; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #374142;"><span style="line-height: 107%; font-family: Kartika, serif; color: #374142;">പള്ളികൂദാശക്കാലം</span> </span></li>
</ul>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal;  font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><span style="font-size: 10pt;">&nbsp;</span></p>	


<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><u><span style="font-size: 18.0pt; font-family: Kartika, serif; color: #c00000;">മംഗലവാര്&zwj;ത്തക്കാലം</span></u></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 26px; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center"><span style="font-size: 10pt;"><span style="color: #000000;">മാര്&zwj;ത്തോമ്മാ ക്രിസ്ത്യാനികളുടെ ആരാധനാവല്&zwj;സരം ആരംഭിക്കുന്നത് മംഗലവാര്&zwj;ത്തക്കാലത്തോടു കൂടിയാണ്. ഡിസംബര്&zwj; 25-ാം തീയതി ആഘോഷിക്കപ്പെടുന്ന ഈശോയുടെ ജനനത്തിന് ഒരുക്കമായുള്ള നാല് ആഴ്ചകള്&zwj; കൂടിയതാണ് ഈ കാലം. തിരുപ്പിറവിക്ക് ഒരുക്കമായി ഡിസംബര്&zwj; 1 മുതല്&zwj; 25 വരെ നോമ്പ് ഈയവസരത്തില്&zwj; ആചരിക്കുന്നതുകൊണ്ടാണ് ഈ കാലത്തിന് &rsquo;25 നോമ്പ്&rsquo; എന്നു പറയുന്നത്. ഈശോയില്&zwj; </span><span style="color: #000000;">പൂര്&zwj;ത്തിയാക്കപ്പെട്ട രക്ഷാകരപ്രവൃത്തികള്&zwj; ആരംഭിക്കുന്നത് അവിടുത്തെ ജനനത്തോടുകൂടിയാണല്ലോ. സുറിയാനി ഭാഷയില്&zwj; &lsquo;സൂബാറാ&rsquo; എന്നാണ് ഈ കാലഘട്ടത്തിന്റെ പേര്. &lsquo;പ്രഖ്യാപനം&rsquo;, &lsquo;അറിയിപ്പ്&rsquo; എന്നൊക്കെയാണ് ഈ പദത്തിന്റെ അര്&zwj;ത്ഥം. രക്ഷകനെ പ്രതീക്ഷിച്ചിരുന്ന മാനവവംശത്തെ സംബന്ധിച്ചിടത്തോളം ഏറ്റവും മംഗളകരമായ വാര്&zwj;ത്തയായിരുന്നല്ലോ ഗബ്രിയേല്&zwj; ദൂതന്&zwj; പരിശുദ്ധ കന്യകാമറിയത്തെ അറിയിച്ചത്. അങ്ങനെ സമയത്തിന്റെ തികവില്&zwj; പൂര്&zwj;ത്തിയായ ഈശോയുടെ മനുഷ്യാവതാര </span><span style="color: #000000;">രഹസ്യത്തിന്റെ പശ്ചാത്തലത്തിലാണ് ഈ കാലം രൂപപ്പെടുത്തിയിരിക്കുന്നത്. അവിടുത്തെ മുന്നോടിയായ സ്നാപകയോഹന്നാന്റെ ജനനത്തെക്കുറിച്ചുള്ള മുന്നറിയിപ്പും അദ്ദേഹത്തിന്റെ ജനനവും അടങ്ങുന്ന മംഗളസംഭവവും ഈ ദിവസങ്ങളില്&zwj; സഭ അനുസ്മരിക്കുന്നു. ഈശോയുടെ മനുഷ്യാവതാര രഹസ്യം കൊണ്ടാടുന്നതിന് ഒരുക്കമായി മനുഷ്യസൃഷ്ടി മുതല്&zwj; ആദിമാതാപിതാക്കളുടെ അനുസരണക്കേടും അതിന്റെ അനന്തരഫലങ്ങളും, അധഃപതിച്ച മനുഷ്യവംശത്തിന്റെ പരിതാപകരമായ അവസ്ഥ, ദൈവം നല്കിയ രക്ഷയുടെ വാഗ്ദാനം, മാനവവംശവുമായി അവിടുന്ന് ചെയ്ത ഉടമ്പടി, രക്ഷകനെക്കുറിച്ചുള്ള പ്രവചനങ്ങള്&zwj; തുടങ്ങിയവയും ഈ കാലത്തില്&zwj; അനുസ്മരിക്കുന്നുണ്ട്. പരിശുദ്ധ ദൈവമാതാവിനു രക്ഷാകരചരിത്രത്തിലുള്ള പങ്കും ഈ കാലത്തില്&zwj; നാം ചിന്താവിഷയമാക്കുന്നു. സ്വന്തം ദയനീയാവസ്ഥയെക്കുറിച്ചു ബോധവാന്മാരായി രക്ഷകനുവേണ്ടി ദാഹിച്ച പഴയനിയമ ജനതയെപ്പോലെ, പുതിയ നിയമത്തിലെ ജനത തങ്ങളുടെ നിസ്സഹായാവസ്ഥയും പാപസാഹചര്യങ്ങളും മനസ്സിലാക്കി മിശിഹായിലേക്കു നടന്നടുക്കണമെന്നും മിശിഹായ്ക്കു പിറക്കുവാന്&zwj; തങ്ങളുടെ ഹൃദയങ്ങളില്&zwj; ഇടം നല്കണമെന്നും ഈ കാലത്തിലെ വി. ഗ്രന്ഥവായനകളും പ്രാര്&zwj;ത്ഥനകളും ഗീതങ്ങളും നമ്മെ അനുസ്മരിപ്പിക്കുന്നു.</span></span></p>


<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><u><span style="font-size: 18.0pt; font-family: Kartika, serif; color: #c00000;">പിറവിക്കാലം</span></u></strong></p>

<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: norm<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">ഈശോമിശിഹായുടെ പിറവിത്തിരുനാള്&zwj; മുതല്&zwj; ദനഹാത്തിരുനാള്&zwj;വരെയുള്ള ദിനങ്ങളാണ് പിറവിക്കാലമായി കണക്കാക്കപ്പെടുന്നത്. ജ്ഞാനികളുടെ സന്ദര്&zwj;ശനവും ഈജിപ്തിലേക്കുള്ള പലായനവും ഈശോയെ ദേവാലയത്തില്&zwj; സമര്&zwj;പ്പിക്കുന്ന സംഭവവുമാണ് പിറവിക്കാലത്തിലെ പ്രധാന ചിന്താവിഷയങ്ങള്&zwj;. ദൈവപുത്രന്റെ ജനനത്തില്&zwj; ഭൂവാസികളും സ്വര്&zwj;ഗ്ഗവാസികളും സന്തോഷത്തിലാറാടി. എന്തുകൊണ്ടെന്നാല്&zwj; രക്ഷയുടെ ആശാകിരണങ്ങള്&zwj; ഉദയംചെയ്തു. ലോകത്തിനു കൈവന്ന ഈ സൌഭാഗ്യത്തില്&zwj; പങ്കുപറ്റാനുള്ള ആഹ്വാനമാണ് ഈ കാലം നല്കുന്നത്. സൌഭാഗ്യത്തില്&zwj; പങ്കുപറ്റുക എന്നാല്&zwj; ക്രിസ്തുവിനെ സ്വന്തമാക്കുകയെന്നാണ്. പാപത്തിനു മരിച്ച്, ക്രിസ്തുവിനെ സ്വന്തമാക്കി, സമാധാനവും പ്രത്യാശയും ഉള്&zwj;ക്കൊള്ളുകയാണ് പിറവിക്കാലത്തിന്റെ ചൈതന്യം.</span></p>
&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: center;" align="center"><span style="color: #000000; font-size: 10pt;"><strong><u><span style="font-size: 18.0pt; line-height: 107%; font-family: Kartika, serif; color: #c00000;">ദനഹാകാലം</span></u></strong> </span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 26px; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center"><span style="color: #000000; font-size: 10pt;">ഉദയം, പ്രത്യക്ഷവത്കരണം, ആവിഷ്കാരം, വെളിപാട് എന്നെല്ലാം അര്&zwj;ത്ഥം വരുന്ന </span><span style="color: #000000; font-size: 10pt;">&lsquo;ദനഹാ&rsquo;ക്കാലത്തില്&zwj;, ജോര്&zwj;ദാന്&zwj; നദിയില്&zwj;വച്ച് ഈശോയുടെ മാമ്മോദീസാവേളയില്&zwj; ആരംഭിച്ച അവിടുത്തെ പ്രത്യക്ഷവത്കരണമാണ് അനുസ്മരിക്കപ്പെടുന്നത്. ഈശോ സ്വയം ലോകത്തിനു വെളിപ്പെടുത്തുകയും പിതാവും പരിശുദ്ധാത്മാവും അതു സാക്ഷ്യപ്പെടുത്തുകയും ചെയ്യുന്നു: &lsquo;ഇവന്&zwj; എന്റെ പ്രിയപുത്രനാകുന്നു; ഇവനില്&zwj; ഞാന്&zwj; പ്രസാദിച്ചിരിക്കുന്നു&rsquo; (മത്താ 3:7). ഈശോമിശിഹായുടെ ത്രിത്വരഹസ്യം അവിടുത്തെ മാമ്മോദീസായില്&zwj; വെളിവാക്കപ്പെട്ടു. </span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 26px; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center"><span style="color: #000000; font-size: 10pt;">ജനുവരി ആറാംതീയതി ആഘോഷിക്കപ്പെടുന്ന കര്&zwj;ത്താവിന്റെ &lsquo;ദനഹാ&rsquo;ത്തിരുനാളിനെ കേരളത്തിന്റെ വടക്കന്&zwj; ഭാഗങ്ങളില്&zwj; &lsquo;പിണ്ടികുത്തി&rsquo;പ്പെരുന്നാളെന്നും തെക്കന്&zwj;ഭാഗങ്ങളില്&zwj; &lsquo;രാക്കുളി&rsquo;പ്പെരുന്നാളെന്നും വിളിക്കാറുണ്ട്. &lsquo;ലോകത്തിന്റെ പ്രകാശമായ&rsquo; മിശിഹായെ ബഹുമാനിക്കുന്നതിനും സ്തുതിക്കുന്നതിനും വാഴപ്പിണ്ടിയില്&zwj; പന്തംകൊളുത്തി അതിനുചുറ്റും പ്രദക്ഷിണംവെച്ചു കൊണ്ട് &lsquo;ദൈവം പ്രകാശമാകുന്നു&rsquo; (ഏല്&zwj; പയ്യ) എന്ന് ആര്&zwj;ത്തുവിളിച്ചിരുന്ന പതിവില്&zwj;നിന്നാണ് &lsquo;പിണ്ടികുത്തി&rsquo; പ്പെരുന്നാള്&zwj; ഉണ്ടായത്. ഈശോയുടെ മാമ്മോദീസായെ സ്മരിച്ചുകൊണ്ട് ഈ തിരുന്നാളിന്റെ തലേദിവസം അടുത്തുള്ള നദിയിലോ കുളത്തിലോ പോയി നമ്മുടെ പൂര്&zwj;വ്വികര്&zwj; നടത്തിയിരുന്ന ആചാരക്കുളി (ൃശൌമഹ യമവേ) യില്&zwj;നിന്നാണ് &lsquo;രാക്കുളി&rsquo; എന്ന പേരു ലഭിച്ചത്. തികച്ചും മതാത്മകമായി നടത്തിയിരുന്ന ഒരു കര്&zwj;മ്മമായിരുന്നു അത്. </span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 26px; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center"><span style="color: #000000; font-size: 10pt;">വെളിപ്പെടുത്തപ്പെട്ട മിശിഹാ രഹസ്യത്തെ തങ്ങളുടെ ജീവിതങ്ങളിലൂടെ സാക്ഷ്യപ്പെടുത്തിയ വിശുദ്ധാത്മാക്കളെ ദനഹാക്കാലത്തെ വെളളിയാഴ്ചകളില്&zwj; സഭ അനുസ്മരിക്കുന്നു. ഈശോയുടെ മാമ്മോദീസ, അവിടുത്തെ പരസ്യജീവിതം, അവിടുത്തെ വ്യക്തിത്വവും മാനുഷിക-ദൈവിക സ്വഭാവങ്ങളും, പിതാവിനോടും പരിശുദ്ധാത്മാവിനോടും അവിടുത്തേക്കുള്ള ഗാഢമായ ബന്ധം, സ്വയം ശൂന്യവത്കരിക്കുന്ന അവിടുത്തെ സ്നേഹം എന്നിവ ഈ കാലത്തിലെ പ്രധാനപ്പെട്ട വിഷയങ്ങളാണ്. ഈശോയുടെ പരസ്യജീവിതവുമായി ബന്ധപ്പെട്ട വി. ഗ്രന്ഥപ്രഘോഷണങ്ങളാണ് (വായനകള്&zwj;) ഈകാലയളവില്&zwj; നാം പ്രധാനമായും ഉപയോഗിക്കുക. ഈശോയുടെ മാമ്മോദീസ അനുസ്മരിക്കുന്നതോടൊപ്പം ഓരോ ക്രൈസ്തവനും തന്റെതന്നെ മാമ്മോദീസാ സ്വീകരണത്തെയും അതിലൂടെ ഏറ്റെടുത്ത ഉത്തരവാദിത്വത്തെയുംപറ്റി ഗാഢമായി ചിന്തിക്കണമെന്ന് ഈ കാലം നമ്മെ ഓര്&zwj;മ്മിപ്പിക്കുന്നു. അങ്ങനെ ഈശോയെ അടുത്തറിഞ്ഞ്, അവിടുത്തെ തീവ്രമായി സ്നേഹിച്ച്, ദൈവമക്കളായി ജീവിക്കാന്&zwj; പരിശ്രമിക്കേണ്ട സന്ദര്&zwj;ഭമാണ് ദനഹാകാലം.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center">&nbsp;</p>

<p style="text-align: center;"><span style="color: #000000; font-size: 10pt;"><strong><u><span style="font-size: 18.0pt; line-height: 107%; font-family: Kartika, serif; color: #c00000;">നോയമ്പ്ക്കാലം</span></u></strong> </span></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">ഈശോയുടെ&nbsp; പരസ്യജീവിതത്തിന്റെ അവസാനത്തിലാണല്ലോ രക്ഷാകര കര്&zwj;മ്മങ്ങളുടെ </span><span style="color: #000000; font-size: 10pt;">പരിസമാപ്തി കുറിക്കുന്ന അവിടുത്തെ പീഡാനുഭവവും മരണവും ഉത്ഥാനവും. ദനഹാക്കാലത്തിനും ഉയിര്&zwj;പ്പുതിരുനാളിനും ഇടയ്ക്കുള്ള ഏഴ് ആഴ്ചകള്&zwj; പ്രാര്&zwj;ത്ഥനയ്ക്കും </span><span style="color: #000000; font-size: 10pt;">പ്രായശ്ചിത്തത്തിനും ഉപവാസത്തിനുമായി നീക്കിവച്ചിരിക്കുന്നു. ഈശോയുടെ നാല്പതു </span><span style="color: #000000; font-size: 10pt;">ദിവസത്തെ ഉപവാസമാണ് &lsquo;വലിയ നോമ്പ്&rsquo; എന്ന പേരില്&zwj; അറിയപ്പെടുന്ന ഈ കാലത്തിന്റെ അടിസ്ഥാനം. എങ്കിലും നാം സാധാരണമായി &lsquo;അമ്പതുനോമ്പ്&rsquo; എന്നാണ് ഈ കാലത്തെ വിളിക്കുക. പക്ഷേ, മാര്&zwj;ത്തോമ്മാ ക്രിസ്ത്യാനികള്&zwj; &lsquo;പേത്തുര്&zwj;ത്താ&rsquo; ഞായര്&zwj; മുതല്&zwj; ഉയിര്&zwj;പ്പുതിരുനാള്&zwj;വരെ നോമ്പുനോക്കിയിരുന്നതാകാം &lsquo;അമ്പതുനോമ്പ്&rsquo; എന്നു പറയാനുള്ള കാരണം. &lsquo;പേത്തുര്&zwj;ത്താ&rsquo; എന്ന സുറിയാനി പദത്തിന്റെ അര്&zwj;ത്ഥം &lsquo;തിരിഞ്ഞുനോക്കല്&zwj;&rsquo;, &lsquo;അനുരഞ്ജനം&rsquo; എന്നൊക്കെയാണ്. അനുതാപത്തിനും അനുരഞ്ജനത്തിനുമായി പ്രത്യേകം മാറ്റിവയ്ക്കപ്പെട്ടിരിക്കുന്ന സമയമാണല്ലോ നോമ്പുകാലം.</span></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">മാമ്മോദീസാവഴി ദൈവമക്കളും പുതിയ മനുഷ്യരുമായിത്തീര്&zwj;ന്ന നാം പാപം വഴി ദൈവത്തില്&zwj;നിന്നകന്നു. മനുഷ്യന്റെ പാപവും അതിന്റെ അനന്തരഫലങ്ങളും അനുതാപത്തിന്റെയും മനഃപരിവര്&zwj;ത്തനത്തിന്റെയും ആവശ്യകതയും, അനുതപിക്കുന്ന പാപികളോടു ദൈവം കാണിക്കുന്ന അനന്തമായ സ്നേഹവും കാരുണ്യവും,ഈശോമിശിഹായുടെ പീഡാനുഭവം, മരണം, സംസ്കാരം എന്നിവയും ഈ കാലത്തിലെ ചിന്താവിഷയങ്ങളാണ്. ദൈവവുമായും മനുഷ്യര്&zwj; തമ്മില്&zwj;ത്തമ്മിലും അനുരഞ്ജിതരാകേണ്ടതിന്റെ ആവശ്യകതയിലേക്കു നോമ്പുകാലം പ്രത്യേകമായി ശ്രദ്ധ തിരിക്കുന്നു. അതുകൊണ്ടാണ് ഈ അവസരത്തില്&zwj; അനുരഞ്ജന കൂദാശ സ്വീകരിക്കാന്&zwj; സഭ വിശ്വാസികളെ പ്രേരിപ്പിക്കുക. </span></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">പ്രലോഭനങ്ങളെ പരാജയപ്പെടുത്തി സ്വജീവിതം പിതാവിനു സമര്&zwj;പ്പിച്ച ഈശോയെപ്പോലെ നമ്മുടെ ദുരാശകളെ ഉന്മൂലനംചെയ്ത്, തീക്ഷ്ണത നിറഞ്ഞ പ്രാര്&zwj;ത്ഥനയിലും ആത്മാര്&zwj;ത്ഥതയുള്ള ഉപവാസത്തിലും ഔദാര്യപൂര്&zwj;വ്വകമായ ദാനധര്&zwj;മ്മപ്രവൃത്തികളിലും ഈ കാലം ചെലവഴിക്കണമെന്ന് സഭ നമ്മെ അനുസ്മരിപ്പിക്കുന്നു. മരണത്തെ പരാജയപ്പെടുത്തി ജീവിതത്തിലേക്കു പ്രവേശിച്ച ഈശോയെപ്പോലെ നമുക്കു പാപത്തിനു മരിച്ച് നിത്യജീവിതത്തിലേക്കു പ്രവേശിക്കാം.</span></p>


<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><u><span style="font-size: 18.0pt; font-family: Kartika, serif; color: #c00000;">ഉയിര്&zwj;പ്പുകാലം</span></u></strong><span style="font-size: 9.0pt; font-family: Arial, sans-serif; color: #555555;"><br /><br /></span></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">ഉയിര്&zwj;പ്പുതിരുനാള്&zwj; മുതല്&zwj; പന്തക്കുസ്താവരെയുള്ള ഏഴ് ആഴ്ചകളാണ് ഉയിര്&zwj;പ്പുകാലം. രക്ഷകന്റെ ഉത്ഥാനത്തിലൂടെ കൈവന്ന പുതുജീവനില്&zwj; ആഹ്ളാദിക്കുന്നതിനുള്ള അവസരമാണിത്. ഈ ആഹ്ളാദത്തിന്റെ പ്രതിഫലനമാണ് ഈ കാലത്തിലെ പ്രാര്&zwj;ത്ഥനകളിലും ഗീതങ്ങളിലും ഉള്ളത്. ഈശോമിശിഹായുടെ ഉത്ഥാനം, പാപത്തിന്റെയും മരണത്തിന്റെയും സാത്താന്റെയും മേല്&zwj; അവിടുന്നു വരിച്ച വിജയം, അതുവഴി ഭോഷത്തത്തിന്റെ ചിഹ്നമായ കുരിശ് രക്ഷയുടെയും മഹത്ത്വത്തിന്റെയും ചിഹ്നമായി മാറുന്നത്, ഈശോയുടെ ഉയിര്&zwj;പ്പ് നമ്മുടെ ഉയിര്&zwj;പ്പിന്റെ അച്ചാരം, അവിടുത്തെ ഉയിര്&zwj;പ്പ് ക്രൈസ്തവവിശ്വാസത്തിന്റെ അടിസ്ഥാനം തുടങ്ങിയവയാണ് ഈ കാലത്തിലെ പ്രധാന ചിന്താവിഷയങ്ങള്&zwj;. </span></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">ആദിമസഭയില്&zwj; മാമ്മോദീസ നല്കിയിരുന്നത് ഉയിര്&zwj;പ്പു തിരുനാളിനോട് അനുബന്ധിച്ചായിരുന്നു. വി. പൌലോസ് അനുസ്മരിപ്പിക്കുന്നതു പോലെ &ldquo;ജ്ഞാനസ്നാനത്താല്&zwj; നാം അവനോടൊത്തു സംസ്കരിക്കപ്പെട്ടു. ക്രിസ്തു മരിച്ചതിനുശേഷം പിതാവിന്റെ മഹത്ത്വത്തില്&zwj; ഉയിര്&zwj;ത്തെഴുന്നേറ്റതുപോലെ നാമും പുതിയ ജീവിതം നയിക്കേണ്ടതിനാണ് അവനോടൊത്തു സംസ്കരിക്കപ്പെട്ടത്&rdquo; (റോമാ 6:4-5). ഉയിര്&zwj;പ്പുകാലത്തിലെ ആദ്യ ആഴ്ച, പുതുതായി മാമ്മോദീസ സ്വീകരിച്ച &ldquo;പുതുക്രിസ്ത്യാനി&rdquo;കളുടെ ആഴ്ചയായി മാറ്റിവച്ചിരുന്നു. അതിനാല്&zwj; അനുകരണാര്&zwj;ഹമായ ഈ പാരമ്പര്യം പുനര്&zwj;ജീവിപ്പിച്ചുകൊണ്ട് ഉയിര്&zwj;പ്പു തിരുനാളിനോടനുബന്ധിച്ചു മാമ്മോദീസ നല്കുക ഉചിതമായിരിക്കും.</span></p>


<p style="text-align: center;"><strong><u><span style="font-size: 18.0pt; line-height: 107%; font-family: Kartika, serif; color: #c00000;">ശ്ളീഹാക്കാലം</span></u></strong></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">പന്തക്കുസ്താത്തിരുനാള്&zwj; തുടങ്ങിയുള്ള ഏഴ് ആഴ്ചകളാണ് ശ്ളീഹാക്കാലം എന്ന പേരില്&zwj; </span><span style="color: #000000; font-size: 10pt;">അറിയപ്പെടുന്നത്. പരിശുദ്ധാത്മാവിന്റെ പ്രവര്&zwj;ത്തനങ്ങള്&zwj;ക്കു പ്രത്യേകമായി പ്രാധാന്യം നല്കുന്ന കാലമാണിത്. രക്ഷാചരിത്രവുമായി അഭേദ്യബന്ധം പുലര്&zwj;ത്തുന്ന ഒരു തിരുനാളാണ് പന്തക്കുസ്ത. ഇസ്രായേല്&zwj;ജനം വിളവെടുപ്പിനോടു ബന്ധപ്പെടുത്തി &lsquo;പന്തക്കുസ്താ&rsquo; ത്തിരുനാള്&zwj; ആഘോഷിച്ചിരുന്നതായി നാം പഴയ നിയമത്തില്&zwj; വായിക്കുന്നുണ്ട്. &lsquo;പന്തക്കുസ്ത&rsquo; എന്ന പദത്തിന്റെ അര്&zwj;ത്ഥം അമ്പത് എന്നാണ്- അമ്പതാം ദിവസത്തെ തിരുനാള്&zwj;. വിളവെടുപ്പിനോടനുബന്ധിച്ചുള്ള ആദ്യഫലസമര്&zwj;പ്പണത്തിന്റെ തിരുനാളായിരുന്നു അത്. പിന്നീടാണ് ഇസ്രായേല്&zwj; ജനം ദൈവത്തിന്റെ ഉടമ്പടിപ്രകാരമുള്ള ദൈവജനമായിത്തീര്&zwj;ന്നതിന്റെ ഓര്&zwj;മ്മയാചരണമായി ഈ തിരുനാള്&zwj; രൂപാന്തരപ്പെട്ടത്. </span></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">പുതിയ നിയമത്തില്&zwj; ഈ തിരുനാളിനു &lsquo;പുതിയ&rsquo; അര്&zwj;ത്ഥം നല്കപ്പെട്ടു. ഉയിര്&zwj;പ്പിനുശേഷം അമ്പതാം ദിവസമാണല്ലോ പരിശുദ്ധാത്മാവ് ശ്ളീഹന്&zwj;മാരുടെമേല്&zwj; എഴുന്നള്ളിയത്. അന്നാണ് സഭ ഔദ്യാഗികമായി &lsquo;ഉദ്ഘാടനം&rsquo; ചെയ്യപ്പെട്ടത്. പുതിയ ദൈവജനത്തിന്റെ ജന്മദിനമാണത്. അന്നു പിതാവായ ദൈവം, ദൈവസ്നേഹം വ്യക്തിത്വം ധരിച്ച പരിശുദ്ധാത്മാവില്&zwj; പുതിയ ഉടമ്പടിക്കു മുദ്രവച്ചു. ഈ ഉടമ്പടി കല്പലകകളിലല്ല, മനുഷ്യഹൃദയങ്ങളിലാണ് ആലേഖനം ചെയ്യപ്പെട്ടിരിക്കുന്നത്. പന്തക്കുസ്തായ്ക്കുശേഷമാണ് പരിശുദ്ധാത്മാവിനാല്&zwj; പൂരിതരായ ശ്ളീഹന്&zwj;മാര്&zwj; പുതിയ ഉടമ്പടിയുടെ സന്ദേശവുമായി ലോകമെങ്ങും പോവുകയും</span></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">സഭാസമൂഹങ്ങള്&zwj;ക്ക് അടിസ്ഥാനമിടുകയും ചെയ്തത്. &lsquo;ശ്ളീഹാ&rsquo; എന്ന പദത്തിന്റെ അര്&zwj;ത്ഥംതന്നെ &ldquo;അയയ്ക്കപ്പെട്ടവന്&zwj;&rdquo; എന്നാണ്. മാമ്മോദീസായും തൈലാഭിഷേകവും സ്വീകരിച്ച എല്ലാവരും &ldquo;അയയ്ക്കപ്പെട്ടവര്&zwj;&rdquo; ആണെന്ന വസ്തുത ഈ കാലം നമ്മെ അനുസ്മരിപ്പിക്കുന്നു. പരിശുദ്ധാത്മാവിന്റെ പ്രവര്&zwj;ത്തനങ്ങള്&zwj;, ശ്ളീഹന്&zwj;മാരും ദൈവജനവുമാകുന്ന സഭയും തമ്മിലുള്ള സുദൃഢമായ ബന്ധം, ആദിമസഭയുടെ ചൈതന്യവും കൂട്ടായ്മയും, സഭയുടെ പ്രേഷിതസ്വഭാവവും ദൌത്യവും എന്നിവയാണ് ഈ കാലത്തിലെ പ്രധാന ചിന്തകള്&zwj;. തങ്ങളുടെ ഗുരുവിന്റെ സന്ദേശവുമായി ലോകം മുഴുവനും ചുറ്റിസഞ്ചരിച്ച്, പുതിയ സഭാസമൂഹങ്ങള്&zwj;ക്കു രൂപംകൊടുത്ത ശ്ളീഹന്മാരുടെ കൂട്ടായ്മയിലും ഐക്യത്തിലും നമുക്കും പങ്കുചേരാം. നമ്മള്&zwj; പരിശുദ്ധാത്മാവിന്റെ ആലയങ്ങളാണെന്ന സത്യം മുറുകെപിടിച്ചുകൊണ്ട്, അവിടുത്തെ നിരന്തരസഹായത്താല്&zwj;,&nbsp;നമുക്കും ശ്ളീഹന്&zwj;മാരെപ്പോലെ മിശിഹായെ പ്രഘോഷിക്കാം</span></p>

<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><u><span style="font-size: 18.0pt; font-family: Kartika, serif; color: #c00000;">കൈത്താക്കാലം</span></u></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center">&nbsp;</p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">നമ്മുടെ കര്&zwj;ത്താവിന്റെ പന്ത്രണ്ടു ശ്ളീഹന്&zwj;മാരെ അനുസ്മരിച്ചുകൊണ്ടാണ് ഈ കാലം </span><span style="color: #000000; font-size: 10pt;">ആരംഭിക്കുന്നത്. സാധാരണമായി ഏഴ് ആഴ്ചകള്&zwj; നീണ്ടുനില്ക്കുന്ന ഈ കാലത്തെ&ldquo;കൈത്താക്കാലം&rdquo; എന്നു വിളിക്കുന്നു. &ldquo;കൈത്ത&rdquo; എന്ന പദത്തിന്റെ അര്&zwj;ത്ഥം &ldquo;വേനല്&zwj;&rdquo; എന്നാണ്. വേനല്&zwj;ക്കാലത്താണല്ലോ വിളവെടുപ്പും ഫലശേഖരണവും നടത്തുക. ശ്ളീഹാക്കാലത്തെ പ്രേഷിതപ്രവര്&zwj;ത്തനത്തിന്റെ ഫലമായി ലോകത്തിന്റെ വിവിധ സ്ഥലങ്ങളില്&zwj; നടപ്പെട്ട സഭാതരു വളര്&zwj;ന്നു പന്തലിച്ചു ഫലം പുറപ്പെടുവിക്കുന്നതിനെയാണ് ഈ കാലം നമ്മെ ഓര്&zwj;പ്പിക്കുക. അതുകൊണ്ട് &ldquo;സഭയുടെ വളര്&zwj;ച്ചയുടെ കാലമായി &rdquo; ഈ കാലം പരിഗണിക്കപ്പെടുന്നു. </span></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">സഭയുടെ വളര്&zwj;ച്ചയെ നിയന്ത്രിക്കുന്ന മാനദണ്ഡം ഈ ലോകത്തില്&zwj; യേശുവിനു സാക്ഷ്യം വഹിക്കുന്ന വ്യക്തികളുടെ ജീവിതമാണ്. അതുകൊണ്ട് സഭയുടെ വിശ്വസ്ത സന്താനങ്ങളായ ശ്ളീഹന്മാരുടെയും രക്തസാക്ഷികളുടെയും ഓര്&zwj;മ്മ ഈ കാലത്തിന്റെ പ്രത്യേകതയാണ്. അവരുടെ ജീവിതചര്യ അനുകരിക്കാന്&zwj; എല്ലാ വിശ്വാസികള്&zwj;ക്കും കടമയുണ്ടെന്ന വസ്തുതയും ഈ കാലം നമ്മെ അനുസ്മരിപ്പിക്കുന്നു. യഥാര്&zwj;ത്ഥവളര്&zwj;ച്ച ആന്തരികനവീകരണത്തില്&zwj; അടങ്ങിയിരിക്കുന്നു. നിയമാനുഷ്ഠാനത്തിലൂടെ മനസ്സിന്റെയും ഹൃദയത്തിന്റെയും നവീകരണം വഴി ഒരു സമൂലപരിവര്&zwj;ത്തനം അനിവാര്യമായിരിക്കുന്നു എന്ന് ഈ കാലം ഓര്&zwj;മ്മിപ്പിക്കുന്നു. </span></p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">കര്&zwj;ത്താവിന്റെ രണ്ടാമത്തെ വരവിനെ സൂചിപ്പിക്കുന്ന ഏലിയാ-സ്ളീവാ- മൂശക്കാലത്തിന്റെ മുന്നോടിയായിട്ടും ഇതിനെ കാണാവുന്നതാണ്. അതുകൊണ്ട് അനുതാപത്തിന്റെയും മാനസാന്തരത്തിന്റെയും ആവശ്യകതയിലേക്കും ഈ കാലം വിരല്&zwj; ചൂണ്ടുന്നു. കര്&zwj;ത്താവിന്റെ വരവിനുവേണ്ടി നാം ഒരുങ്ങിയിരിക്കണം. പാപത്തോടു വിടപറഞ്ഞ്, ജീവിത വിശുദ്ധീകരണത്തിലൂടെ നമുക്കു വ്യാപരിക്കാം.</span></p>



<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><u><span style="font-size: 18.0pt; font-family: Kartika, serif; color: #c00000;">എലിയാ ശ്ലീഹ മൂശാ കാലം</span></u></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center">&nbsp;</p>
<p style="text-align: justify;"><span style="color: #000000; font-size: 10pt;">ഏലിയാ-സ്ളീവാ-മൂശക്കാലങ്ങള്&zwj; കുരിശിന്റെ വിജയവും കര്&zwj;ത്താവിന്റെ രണ്ടാമത്തെ ആഗമനവും സൂചിപ്പിക്കുന്നു. സെപ്തംബര്&zwj; 14-ാം തീയതി ആചരിക്കുന്ന കുരിശിന്റെ പുകഴ്ചയാണ് ഈ കാലഘട്ടത്തിന്റെ കേന്ദ്രബിന്ദു. മിശിഹായുടെ രണ്ടാമത്തെ വരവിനു മുമ്പായി ഏലിയാ വരുമെന്നും (മലാക്കി4:5) വിനാശത്തിന്റെ പുത്രനുമായി തര്&zwj;ക്കിച്ച് അവന്റെ തെറ്റിനെ ലോകത്തിനു ബോദ്ധ്യപ്പെടുത്തുമെന്നും ആദിമസഭ വിശ്വസിച്ചുപോന്നു. കര്&zwj;ത്താവിന്റെ രൂപാന്തരീകരണവേളയില്&zwj; അവിടുത്തോടൊപ്പം ഏലിയായും ഉണ്ടായിരുന്നുവെന്ന വസ്തുത ഈ വിശ്വാസത്തിന് ആക്കം വര്&zwj;ദ്ധിപ്പിച്ചു. കര്&zwj;ത്താവിന്റെ രൂപാന്തരീകരണം അവിടുത്തെ രണ്ടാമത്തെ വരവിന്റെ പ്രതീകവുമാണല്ലോ. രൂപാന്തരപ്പെട്ട സമയത്ത് മൂശയും അവിടുത്തോടൊപ്പം ഉണ്ടായിരുന്നതായിരിക്കാം സ്ളീവ നടുവില്&zwj; വരത്തക്കവിധം ഏലിയാ- സ്ളീവാ-മൂശക്കാലങ്ങള്&zwj; രൂപപ്പെട്ടതിനു കാരണം. ലോകാവസാനം, മരണം, അവസാനവിധി എന്നിവയാണ് ഈ കാലങ്ങളിലെ പ്രധാന വിഷയങ്ങള്&zwj;. അതോടൊപ്പം, പിശാചിന്റെ പ്രലോഭനങ്ങള്&zwj;ക്കെതിരെ ജാഗ്രത പുലര്&zwj;ത്തി, പാപത്തെ തുടച്ചുമാറ്റാനുള്ള ആഹ്വാനവും നമുക്കു നല്കുന്നു. മിശിഹായുടെ ദ്വിതീയാഗമനത്തിനുമുമ്പ് ആകാശമദ്ധ്യത്തില്&zwj; മഹത്ത്വപൂര്&zwj;ണ്ണമായി പ്രത്യക്ഷപ്പെടുമെന്ന് അവിടുന്ന് പറഞ്ഞിട്ടുള്ള അടയാളം (മത്താ 24:30) കുരിശാണെന്ന വിശ്വാസം ആദിമസഭയില്&zwj; ഉണ്ടായിരുന്നു. അതുകൊണ്ട് കുരിശിന്റെ ശക്തിയും വിജയവും ഈ കാലത്തില്&zwj; നാം പ്രത്യേകമായി അനുസ്മരിക്കുന്നുണ്ട്.</span></p>

<p style="margin: 0cm 0cm 0.0001pt; text-align: justify; text-indent: 36pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: justify; text-indent: 36pt; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center"><strong><u><span style="font-size: 18.0pt; font-family: Kartika, serif; color: #c00000;">പള്ളികൂദാശക്കാലം</span></u></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: center; line-height: normal; background: white; font-size: 11pt; font-family: Calibri, sans-serif;" align="center">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 21pt; background: white; font-size: 11pt; font-family: Calibri, sans-serif; text-align: justify;" align="center"><span style="font-size: 10pt; font-family: Kartika, serif; color: #000000; ">ആരാധനാവത്സരത്തിലെ അവസാനത്തെ നാല് ആഴ്ചകളാണ് പള്ളിക്കൂദാശക്കാലത്തിലുള്ളത്. പള്ളിക്കുദാശ എന്നാല്&zwj; സഭാസമര്&zwj;പ്പണം എന്നാണര്&zwj;ത്ഥം. ഇതിന്റെ ആദ്യത്തെ ഞായറാഴ്ച സഭാപ്രതിഷ്ഠയുടെ അനുസ്മരണം ആചരിക്കുന്നു. മിശിഹാ തന്റെ മണവാട്ടിയായ സഭയെ അവസാനവിധിക്കുശേഷം പിതാവിനു സമര്&zwj;പ്പിക്കുന്നതിനെ ഈ കാലത്തിന്റെ ആരംഭത്തില്&zwj;ത്തന്നെ നാം അനുസ്മരിക്കുന്നു. യുഗാന്തത്തില്&zwj; സഭ തന്റെ മക്കളോടൊപ്പം സ്വര്&zwj;ഗ്ഗീയ ഓര്&zwj;ശ്ളേമാകുന്ന മണവറയില്&zwj; തന്റെ വരനെ കണ്ടുമുട്ടുന്നു. സഭാമക്കളെ കാത്തിരിക്കുന്ന നിത്യസൌഭാഗ്യത്തിന്റെ മുന്നാസ്വാദനം നല്&zwj;കുന്ന കാലഘട്ടമാണിത്.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: justify; line-height: normal; font-size: 11pt; font-family: Calibri, sans-serif;">&nbsp;</p>
<p style="margin: 0cm 0cm 0.0001pt; text-align: justify; line-height: 21pt; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 10pt; font-family: Kartika, serif; color: #000000;">മിശിഹായുടെ മനുഷ്യാവതാര രഹസ്യത്തില്&zwj; പങ്കുചേര്&zwj;ന്നുകൊണ്ട് ദൈവജനം ആരംഭിക്കുന്ന വിശ്വാസതീര്&zwj;ത്ഥാടനം തിരുസഭയുടെ സ്വര്&zwj;ഗ്ഗീയ മഹത്വരഹസ്യത്തില്&zwj; പൂര്&zwj;ത്തിയാകും വിധമാണ് ആരാധനാവത്സരം സംവിധാനം ചെയ്തിരിക്കുന്നത്.</span></p>
				</div>					
				
			
			
		</div>
	</section>
	<!--================End About Area =================-->


@endsection